- id: lint
  name: Lint JS & TS
  entry: eslint
  language: node
  args:
    - '--fix'
  additional_dependencies:
    - '@paulhfischer/prettier-config@1.6.0'
    - '@typescript-eslint/eslint-plugin@5.55.0'
    - '@typescript-eslint/parser@5.55.0'
    - eslint@8.36.0
    - eslint-config-airbnb-base@15.0.0
    - eslint-config-airbnb-typescript@17.0.0
    - eslint-config-prettier@8.7.0
    - eslint-plugin-html@7.1.0
    - eslint-plugin-import@2.27.5
    - eslint-plugin-jinja2-processor@1.2.0
    - eslint-plugin-prettier@4.2.1
    - prettier@2.8.4
  types:
    - file
  files: \.(js|ts|html|php)$
  exclude: (^node_modules|\.min\.js$)
