- id: lint
  name: Lint JS & TS
  entry: eslint
  language: node
  args:
    - '--fix'
  additional_dependencies:
    - '@paulhfischer/prettier-config@1.1.0'
    - '@typescript-eslint/eslint-plugin@5.11.0'
    - '@typescript-eslint/parser@5.11.0'
    - eslint@8.8.0
    - eslint-config-airbnb-base@15.0.0
    - eslint-config-airbnb-typescript@16.1.0
    - eslint-config-prettier@8.3.0
    - eslint-plugin-html@6.2.0
    - eslint-plugin-import@2.25.4
    - eslint-plugin-jinja2-processor@1.0.0
    - eslint-plugin-prettier@4.0.0
    - prettier@2.5.1
  types:
    - file
  files: \.(js|ts|html|php)$
  exclude: (^node_modules|\.min\.js$)
