- id: lint
  name: Lint JS & TS
  entry: eslint
  language: node
  args:
    - '--fix'
  additional_dependencies:
    - '@paulhfischer/prettier-config@1.10.0'
    - '@typescript-eslint/eslint-plugin@6.18.0'
    - '@typescript-eslint/parser@6.18.0'
    - eslint@8.56.0
    - eslint-config-airbnb-base@15.0.0
    - eslint-config-airbnb-typescript@17.1.0
    - eslint-config-prettier@9.1.0
    - eslint-plugin-html@7.1.0
    - eslint-plugin-import@2.29.1
    - eslint-plugin-jinja2-processor@1.2.0
    - eslint-plugin-prettier@5.1.2
    - prettier@3.1.1
  types:
    - file
  files: \.(js|ts|html|php)$
  exclude: (^node_modules|\.min\.js$)
