- id: lint
  name: Lint JS & TS
  entry: eslint
  language: node
  args:
    - '--fix'
  additional_dependencies:
    - '@paulhfischer/prettier-config@1.13.0'
    - '@typescript-eslint/eslint-plugin@7.2.0'
    - '@typescript-eslint/parser@7.2.0'
    - eslint@8.57.0
    - eslint-config-airbnb-base@15.0.0
    - eslint-config-airbnb-typescript@18.0.0
    - eslint-config-prettier@9.1.0
    - eslint-plugin-html@8.0.0
    - eslint-plugin-import@2.29.1
    - eslint-plugin-jinja2-processor@1.2.0
    - eslint-plugin-prettier@5.1.3
    - prettier@3.2.5
  types:
    - file
  files: \.(js|ts|html|php)$
  exclude: (^node_modules|\.min\.js$)
